[versions]
kotlin = "2.4.0"
ofdKtProto = "2.0.3"
detekt = "1.23.8"
ofdNetworkClient = "1.0.0"
serialization = "1.11.0"
coroutines = "1.11.0"
protobufJava = "4.35.1"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
ofd-kt-proto = { group = "io.github.texport", name = "ofd-kt-proto-v203", version.ref = "ofdKtProto" }
protobuf-java = { group = "com.google.protobuf", name = "protobuf-java", version.ref = "protobufJava" }
ofd-network-client = { group = "kz.mybrain", name = "ofd-network-client", version.ref = "ofdNetworkClient" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

