[versions]
kotlin = "2.4.0"
ofdKtProto = "2.0.3-2"
detekt = "1.23.8"
ofdNetworkClient = "1.1.0"
serialization = "1.11.0"
coroutines = "1.11.0"
nmcp = "1.5.0"
wire = "5.1.0"
javaTargetCore = "17"

[libraries]
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
ofd-kt-proto = { group = "io.github.texport", name = "ofd-kt-proto", version.ref = "ofdKtProto" }
ofd-network-client = { group = "io.github.texport", name = "ofd-network-client", version.ref = "ofdNetworkClient" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
